// Copyright 2026 The OpenChoreo Authors
// SPDX-License-Identifier: Apache-2.0

import type { ResourceNodeType } from '../types/nodes';
// Generated by fantasticon — maps icon names to decimal codepoints
import codepointsMap from '../../../extension/resources/openchoreo-icons.json';

/** Convert decimal codepoints to characters at import time. */
const FONT_CODEPOINTS: Record<string, string> = Object.fromEntries(
  Object.entries(codepointsMap as Record<string, number>).map(
    ([name, code]) => [name, String.fromCodePoint(code)],
  ),
);

/**
 * Maps resource types to custom font icon names.
 * Mirrors MUI_ICON_MAP from extension's shared.ts.
 */
const FONT_ICON_MAP: Partial<Record<ResourceNodeType, string>> = {
  namespace: 'apartment',
  project: 'dashboard',
  component: 'memory',
  workload: 'storage',
  environment: 'cloud',
  'data-plane': 'dns',
  'cluster-data-plane': 'dns',
  'workflow-plane': 'build',
  'cluster-workflow-plane': 'build',
  'observability-plane': 'visibility',
  'cluster-observability-plane': 'visibility',
  'component-type': 'category',
  'cluster-component-type': 'category',
  trait: 'extension',
  'cluster-trait': 'extension',
  workflow: 'play-circle-outline',
  'cluster-workflow': 'play-circle-outline',
  'deployment-pipeline': 'account-tree',
  'namespace-role': 'security',
  'cluster-role': 'security',
  'namespace-role-binding': 'link',
  'cluster-role-binding': 'link',
};

/**
 * Fallback codicon map for types without custom font icons.
 */
const CODICON_MAP: Record<ResourceNodeType, string> = {
  namespace: 'symbol-namespace',
  project: 'project',
  component: 'package',
  'component-category': 'symbol-folder',
  'workflow-run': 'debug-start',
  'component-release': 'tag',
  'release-binding': 'link',
  workload: 'server-process',
  'deployment-pipeline': 'git-merge',
  'infra-category': 'symbol-folder',
  environment: 'cloud',
  'data-plane': 'server',
  'workflow-plane': 'wrench',
  'observability-plane': 'eye',
  'component-type': 'symbol-class',
  workflow: 'play-circle',
  trait: 'extensions',
  'secret-reference': 'key',
  'namespace-role': 'shield',
  'namespace-role-binding': 'person',
  'cluster-role': 'shield',
  'cluster-role-binding': 'person',
  'cluster-component-type': 'symbol-class',
  'cluster-workflow': 'play-circle',
  'cluster-trait': 'extensions',
  'cluster-data-plane': 'server',
  'cluster-workflow-plane': 'wrench',
  'cluster-observability-plane': 'eye',
  'workflow-run-step': 'circle-outline',
  'k8s-resource': 'symbol-object',
  'k8s-pod': 'server-process',
  'k8s-rendered-release': 'layers',
  'release-binding-placeholder': 'circle-outline',
  'no-connection': 'warning',
  empty: 'info',
};

/** Phase → codicon + CSS color class for workflow runs/steps. */
export function phaseIcon(phase: string): { codicon: string; colorClass: string } {
  switch (phase) {
    case 'Succeeded': return { codicon: 'pass', colorClass: 'icon-success' };
    case 'Failed':    return { codicon: 'error', colorClass: 'icon-error' };
    case 'Running':   return { codicon: 'sync', colorClass: 'icon-running' };
    case 'Pending':   return { codicon: 'clock', colorClass: '' };
    case 'Skipped':   return { codicon: 'debug-step-over', colorClass: '' };
    case 'Error':     return { codicon: 'warning', colorClass: 'icon-warning' };
    default:          return { codicon: 'circle-outline', colorClass: '' };
  }
}

/** K8s health status → codicon + CSS color class. */
export function healthIcon(status: string): { codicon: string; colorClass: string } {
  switch (status) {
    case 'Healthy':     return { codicon: 'pass', colorClass: 'icon-success' };
    case 'Degraded':    return { codicon: 'warning', colorClass: 'icon-warning' };
    case 'Progressing': return { codicon: 'sync', colorClass: 'icon-running' };
    case 'Missing':     return { codicon: 'error', colorClass: 'icon-error' };
    default:            return { codicon: 'question', colorClass: '' };
  }
}

export type ResolvedIcon =
  | { kind: 'codicon'; codicon: string; colorClass: string }
  | { kind: 'font'; char: string };

/** Get the font character for a named icon. */
export function getFontChar(iconName: string): string | undefined {
  return FONT_CODEPOINTS[iconName];
}

/** Resolve the icon for a node — custom font if available, codicon fallback. */
export function resolveNodeIcon(
  type: ResourceNodeType,
  statusPhase?: string,
  healthStatus?: string,
  iconOverride?: string,
): ResolvedIcon {
  // Status/health icons are always codicons (colored)
  if (statusPhase) return { kind: 'codicon', ...phaseIcon(statusPhase) };
  if (healthStatus) return { kind: 'codicon', ...healthIcon(healthStatus) };

  // Check for custom font icon (with override support)
  const fontIconName = iconOverride
    ? FONT_ICON_MAP[iconOverride as ResourceNodeType]
    : FONT_ICON_MAP[type];
  if (fontIconName) {
    const char = FONT_CODEPOINTS[fontIconName];
    if (char) return { kind: 'font', char };
  }

  // Codicon fallback (with override support)
  if (iconOverride) {
    const overrideIcon = CODICON_MAP[iconOverride as ResourceNodeType];
    if (overrideIcon) return { kind: 'codicon', codicon: overrideIcon, colorClass: '' };
  }
  return { kind: 'codicon', codicon: CODICON_MAP[type] ?? 'circle-outline', colorClass: '' };
}
